apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: grafana
 namespace: argocd
spec:
  destination:
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: subchart/grafana
    repoURL: https://github.com/projectlemontwist/argocdtest.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true