apiVersion: v2
name: grafana
description: A helm chart for grafana
type: application
version: 0.0.0
appVersion: "10.4.0"
dependencies:
- name: grafana
  version: "7.3.7"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled